version: '2'
services:

    # Redis
    redis:
        image: redis
        ports:
            - "6379:6379"

    # Mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    # ELS
    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"

    # API
    unicef-backend:
        image: unicef-backend
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        env_file: .env
        volumes:
            - ./unicef_backend:/app
            - ./preprocess/actions.json:/app/actions.json
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        links:
            - redis:redis
        entrypoint: ["python", "manage.py", "runserver",  "--host", "0.0.0.0", "--port", "5000", "--debug"]

    # Celery worker
    worker:
        image: unicef-backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - ./unicef_backend:/app
        depends_on:
            - redis
            - mongo
        links:
            - redis:redis
            - mongo:mongo
        entrypoint: ["celery", "-A", "celery_worker:celery", "worker", "--loglevel=DEBUG"]

    # Celery beat
    beat:
        image: unicef-backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - ./unicef_backend:/app
        depends_on:
            - redis
        links:
            - redis:redis
        entrypoint: ["celery", "-A", "celery_worker:celery", "beat", "--loglevel=INFO"]
